INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (1, '1', 'Sofia Municipality', 'Sofia', 'White street', '6', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (2, '2', 'Moscow Municipality', 'Moscow', 'Moscow street', '120', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (3, '3', 'Berlin Municipality', 'Berlin', 'New street', '122', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (4, '4', 'London Municipality', 'London', 'Flight street', '90', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (5, '5', 'Athens Municipality', 'Athena', 'Green street', '65', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (6, '6', 'Istanbul Municipality', 'Istanbul', 'View street', '41', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (7, '6', 'Ankara Municipality', 'Ankara', 'Turkey street', '141', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (8, '7', 'Bucharest Municipality', 'Bucharest', 'Capital street', '99', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (9, '8', 'Vienna Municipality', 'Vienna', 'Red street', '78', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (10, '9', 'Rome Municipality', 'Rome', 'Rome street', '87', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (11, '10', 'Madrid Municipality', 'Madrid', 'Sky street', '111', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (12, '11', 'Warsaw Municipality', 'Warsaw', 'Polland street', '100', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (13, '12', 'Paris Municipality', 'Paris', 'Street street', '24', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (14, '13', 'Ljubljana Municipality', 'Ljubljana', 'Blue street', '88', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (15, '14', 'Bratislava Municipality', 'Bratislava', 'Bratislava street', '80', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (16, '15', 'Copenhagen Municipality', 'Copenhagen', 'Focus street', '90', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (17, '2', 'Saint Petersburg Municipality', 'Saint Petersburg', 'Petersburg street', '199', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (18, '12', 'Lyon Municipality', 'Lyon', 'France street', '165', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (19, '10', 'Barcelona Municipality', 'Barcelona', 'View street', '178', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (20, '3', 'Frankfurt Municipality', 'Frankfurt', 'Frankfurt street', '155', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (21, '9', 'Milano Municipality', 'Milano', 'See street', '139', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (22, '10', 'Sevilla Municipality', 'Sevilla', 'Sevilla New street', '75', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (23, '3', 'Hamburg Municipality', 'Hamburg', 'New street', '138', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (24, '9', 'Florence Municipality', 'Florence', 'Florence street', '88', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (25, '12', 'Toulouse Municipality', 'Toulouse', 'France New street', '77', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (26, '8', 'Linz Municipality', 'Linz', 'Linz Old street', '32', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (27, '4', 'Edinburgh Municipality', 'Edinburgh', 'Edinburgh Old street', '39', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (28, '3', 'Munich Municipality', 'Munich', 'Germany street', '81', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (29, '7', 'Timisoara Municipality', 'Timisoara', 'Romania Old street', '19', '1');
INSERT INTO LOCATION (ID, COUNTRY_ID, REGION, CITY, STREET, STREET_NUMBER, CONTACTS_ID) VALUES (30, '15', 'Aalborg Municipality', 'Aalborg', 'View street', '90', '1');